# Generated by Django 2.2.6 on 2019-12-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingDapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
