# Generated by Django 2.2.6 on 2019-11-10 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votingDapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('학사제도', '학사제도'), ('시설', '시설'), ('교직원', '교직원')], max_length=20),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('문과대학', '문과대학'), ('이과대학', '이과대학'), ('불교대학', '불교대학'), ('법과대학', '법과대학'), ('사회과학대학', '사회과학대학'), ('경찰사법대학', '경찰사법대학'), ('경영대학', '경영대학'), ('바이오시스템대학', '바이오시스템대학'), ('공과대학', '공과대학'), ('사범대학', '사범대학'), ('예술대학', '예술대학'), ('약학대학', '약학대학'), ('미래융합대학', '미래융합대학')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='votingDapp.Department'),
        ),
    ]
